version: '3'

services:

  flaskapp:
    build: .
    volumes:
      - .:/app/
      - ./static:/opt/services/flaskapp/src
    networks:
      - nginx_network
    ports:
      - 5000
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./ssl-certificates:/etc/nginx/certs
    depends_on:
      - flaskapp
    networks:
      - nginx_network

  icecast:
    image: moul/icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=$ICECAST_SOURCE_PASSWORD
      - ICECAST_ADMIN_PASSWORD=$ICECAST_ADMIN_PASSWORD
      - ICECAST_PASSWORD=$ICECAST_PASSWORD
      - ICECAST_RELAY_PASSWORD=$ICECAST_RELAY_PASSWORD
      - ICECAST_HOSTNAME=$ICECAST_HOSTNAME
    ports:
      - 8000:8000
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge