name: CD-to-Home-Server
env:
  VERSION: "2.2"

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Make sure ssh is installed
      run: sudo apt-get update && sudo apt-get install ssh

    - name: Create ssh secret key
      run: |
        mkdir .ssh &&\
        touch ~/.ssh/id_rsa &&\
        tee > ~/.ssh/id_rsa <<EOF
        ${{ secrets.SSH_PRIVATE_KEY }}
        EOF

    - name: Connect to server and make it pull new changes from repo
      run: |
        ssh -o StrictHostKeyChecking=no \
        -i ~/.ssh/id_rsa \
        user@93.75.92.82 \
        'pkill gunicorn &&\
        cd ~/tusovka-flask-webapp &&\
        git fetch origin master &&\
        git reset --hard origin/master &&\
        git clean -f -d &&\
        source env/bin/activate &&\
        pip install -r requirements.txt &&\
        nohup make prod 1>> ~/logs/tusovka.out 2>> ~/logs/tusovka.err < /dev/null &'
