# This is a basic workflow to help you get started with Actions

name: Staging-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Start a gunicorn and see if crashes
      run: |
        sudo apt-get install python3-venv
        python3 -m venv env;
        source env/bin/activate;
        pip install -r requirements.txt;
        gunicorn -b 127.0.0.1:8000 application:application --access-logfile .log/access.log --error-logfile .log/general.log;
        curl 127.0.0.1:8000/;

    # Runs a set of commands using the runners shell
    - name: If crashes print logs
      if: failure()
      run: cat ./*.log
